### ISSUE TITLE
添加渠道模型名称超长崩溃，重启应用后循环崩溃，无法恢复

### ISSUE THREAD

**Issue by tzhao11** [Calcium-Ion/new-api#691]
**例行检查**

[//]: # (方框内删除已有的空格，填 x 号)
+ [x] 我已确认目前没有类似 issue
+ [x] 我已确认我已升级到最新版本
+ [x] 我已完整查看过项目 README，尤其是常见问题部分
+ [x] 我理解并愿意跟进此 issue，协助测试和提供反馈 
+ [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**问题描述**

new-api v0.4.5.2

添加渠道，添加名称超长的模型，应用崩溃，报错如下：
```
new-api  | 2025/01/05 15:02:24 /build/model/ability.go:155 Error 1406: Data too long for column 'model' at row 10
new-api  | [6.016ms] [rows:0] INSERT INTO `abilities` (`group`,`model`,`channel_id`,`enabled`,`priority`,`weight`,`tag`) VALUES ('default','magnum-v4-22b',1,true,0,0,''),('default','magnum-v4-12b',1,true,0,0,''),('default','dolphin-2.9.3-mistral-nemo-12b',1,true,0,0,''),('default','causallm-14b-dpo-alpha',1,true,0,0,''),('default','lmstudio-community/mistral-nemo-instruct-2407',1,true,0,0,''),('default','mistral-nemo-instruct-2407@8bit',1,true,0,0,''),('default','mistral-nemo-instruct-2407@4bit',1,true,0,0,''),('default','qwen2.5-32b-instruct',1,true,0,0,''),('default','qwen2.5-14b-instruct',1,true,0,0,''),('default','sakurallm/sakura-14b-qwen2.5-v1.0-gguf/sakura-14b-qwen2.5-v1.0-q6k.gguf',1,true,0,0,''),('default','sakurallm/sakura-14b-qwen2.5-v1.0-gguf/sakura-14b-qwen2.5-v1.0-iq4xs.gguf',1,true,0,0,''),('default','qwen2.5-7b-instruct-mlx@8bit',1,true,0,0,''),('default','qwen2.5-7b-instruct-mlx@4bit',1,true,0,0,''),('default','meta-llama-3.1-8b-instruct',1,true,0,0,''),('default','qwen2.5-14b-instruct-mlx',1,true,0,0,''),('default','text-embedding-nomic-embed-text-v1.5',1,true,0,0,'')
new-api  | [GIN] 2025/01/05 - 15:02:24 | 20250105150223964462976KK4TGjNQ | 200 |   43.034446ms |   192.168.117.1 |    POST /api/channel/
new-api  | [SYS] 2025/01/05 - 15:02:30 | 任务进度轮询开始 
new-api  | [SYS] 2025/01/05 - 15:02:30 | 任务进度轮询完成 
new-api  | [SYS] 2025/01/05 - 15:02:44 | syncing channels from database 
new-api  | [SYS] 2025/01/05 - 15:02:44 | syncing options from database 
new-api  | panic: assignment to entry in nil map
new-api  | 
new-api  | goroutine 40 [running]:
new-api  | one-api/model.InitChannelCache()
new-api  |      /build/model/cache.go:143 +0x688
new-api  | one-api/model.SyncChannelCache(0x3c)
new-api  |      /build/model/cache.go:171 +0x44
new-api  | created by main.main in goroutine 1
new-api  |      /build/main.go:87 +0x3f0
new-api  | [SYS] 2025/01/05 - 15:02:44 | Support for .env file is disabled 
new-api  | [SYS] 2025/01/05 - 15:02:44 | New API v0.4.5.2 started 
new-api  | [SYS] 2025/01/05 - 15:02:44 | using MySQL as database 
new-api  | [SYS] 2025/01/05 - 15:02:44 | database migration started 
new-api  | [SYS] 2025/01/05 - 15:02:44 | database migrated 
new-api  | [SYS] 2025/01/05 - 15:02:44 | SYNC_FREQUENCY not set, use default value 60 
new-api  | [SYS] 2025/01/05 - 15:02:44 | Redis is enabled 
new-api  | [SYS] 2025/01/05 - 15:02:44 | memory cache enabled 
new-api  | [SYS] 2025/01/05 - 15:02:44 | sync frequency: 60 seconds 
new-api  | panic: assignment to entry in nil map
```

重启应用后陷入crash loop，无法恢复：
```
new-api  | [SYS] 2025/01/05 - 15:28:59 | New API v0.4.5.2 started 
new-api  | [SYS] 2025/01/05 - 15:28:59 | using MySQL as database 
new-api  | [SYS] 2025/01/05 - 15:28:59 | database migration started 
new-api  | [SYS] 2025/01/05 - 15:28:59 | database migrated 
new-api  | [SYS] 2025/01/05 - 15:28:59 | SYNC_FREQUENCY not set, use default value 60 
new-api  | [SYS] 2025/01/05 - 15:28:59 | Redis is enabled 
new-api  | [SYS] 2025/01/05 - 15:28:59 | memory cache enabled 
new-api  | [SYS] 2025/01/05 - 15:28:59 | sync frequency: 60 seconds 
new-api  | panic: assignment to entry in nil map
new-api  | 
new-api  | goroutine 1 [running]:
new-api  | one-api/model.InitChannelCache()
new-api  |      /build/model/cache.go:143 +0x688
new-api  | main.main()
new-api  |      /build/main.go:83 +0x380
new-api  | [SYS] 2025/01/05 - 15:28:59 | database migrated 
new-api  | [SYS] 2025/01/05 - 15:28:59 | SYNC_FREQUENCY not set, use default value 60 
new-api  | [SYS] 2025/01/05 - 15:28:59 | Redis is enabled 
new-api  | [SYS] 2025/01/05 - 15:28:59 | memory cache enabled 
new-api  | [SYS] 2025/01/05 - 15:28:59 | sync frequency: 60 seconds 
new-api  | panic: assignment to entry in nil map
new-api  | 
new-api  | goroutine 1 [running]:
new-api  | one-api/model.InitChannelCache()
new-api  |      /build/model/cache.go:143 +0x688
new-api  | main.main()
new-api  |      /build/main.go:83 +0x380
new-api  | [SYS] 2025/01/05 - 15:29:00 | database migrated 
new-api  | [SYS] 2025/01/05 - 15:29:00 | SYNC_FREQUENCY not set, use default value 60 
new-api  | [SYS] 2025/01/05 - 15:29:00 | Redis is enabled 
new-api  | [SYS] 2025/01/05 - 15:29:00 | memory cache enabled 
new-api  | [SYS] 2025/01/05 - 15:29:00 | sync frequency: 60 seconds 
new-api  | panic: assignment to entry in nil map
new-api  | 
new-api  | goroutine 1 [running]:
new-api  | one-api/model.InitChannelCache()
new-api  |      /build/model/cache.go:143 +0x688
new-api  | main.main()
new-api  |      /build/main.go:83 +0x380
new-api  | [SYS] 2025/01/05 - 15:29:02 | database migrated 
new-api  | [SYS] 2025/01/05 - 15:29:02 | SYNC_FREQUENCY not set, use default value 60 
new-api  | [SYS] 2025/01/05 - 15:29:02 | Redis is enabled 
new-api  | [SYS] 2025/01/05 - 15:29:02 | memory cache enabled 
new-api  | [SYS] 2025/01/05 - 15:29:02 | sync frequency: 60 seconds 
new-api  | panic: assignment to entry in nil map
new-api  | 
new-api  | goroutine 1 [running]:
new-api  | one-api/model.InitChannelCache()
new-api  |      /build/model/cache.go:143 +0x688
new-api  | main.main()
new-api  |      /build/main.go:83 +0x380
new-api  | [SYS] 2025/01/05 - 15:29:06 | database migrated 
new-api  | [SYS] 2025/01/05 - 15:29:06 | SYNC_FREQUENCY not set, use default value 60 
new-api  | [SYS] 2025/01/05 - 15:29:06 | Redis is enabled 
new-api  | [SYS] 2025/01/05 - 15:29:06 | memory cache enabled 
new-api  | [SYS] 2025/01/05 - 15:29:06 | sync frequency: 60 seconds 
new-api  | panic: assignment to entry in nil map
...
```

**复现步骤**

使用以下docker-compose.yml 启动new-api
```yaml
services:
  new-api:
    image: calciumion/new-api:latest
    container_name: new-api
    restart: always
    command: --log-dir /app/logs
    # ports:
    #   - "3000:3000"
    volumes:
      - new_api_data:/data
      - new_api_logs:/app/logs
    environment:
      - SQL_DSN=root:123456@tcp(mysql:3306)/new-api  # Point to the mysql service
      - REDIS_CONN_STRING=redis://redis
      - TZ=Asia/Shanghai
    #      - SESSION_SECRET=random_string  # 多机部署时设置，必须修改这个随机字符串！！！！！！！
    #      - NODE_TYPE=slave  # Uncomment for slave node in multi-node deployment
    #      - SYNC_FREQUENCY=60  # Uncomment if regular database syncing is needed
    #      - FRONTEND_BASE_URL=https://openai.justsong.cn  # Uncomment for multi-node deployment with front-end URL
    depends_on:
      - redis
      - mysql
    healthcheck:
      test: [ "CMD-SHELL", "wget -q -O - http://localhost:3000/api/status | grep -o '\"success\":\\s*true' | awk -F: '{print $2}'" ]
      interval: 30s
      timeout: 10s
      retries: 3

  redis:
    image: redis:latest
    # container_name: redis
    restart: always

  mysql:
    image: mysql:8.2
    # container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 123456  # Ensure this matches the password in SQL_DSN
      MYSQL_DATABASE: new-api
    volumes:
      - new_api_mysql_data:/var/lib/mysql
    # ports:
    #   - "3306:3306"  # If you want to access MySQL from outside Docker, uncomment

volumes:
  new_api_mysql_data:
  new_api_data:
  new_api_logs:
```

添加渠道，输入名称超长的模型，例如sakurallm/sakura-14b-qwen2.5-v1.0-gguf/sakura-14b-qwen2.5-v1.0-q6k.gguf，应用循环崩溃，无法恢复

**预期结果**

模型添加成功
