### ISSUE TITLE
启动容器没网提示failed to get gpt-3.5-turbo

### ISSUE THREAD

**Issue by ft4710403** [Calcium-Ion/new-api#837]
我希望在离线环境中使用 new-aip，但是 如果启动的时候没网，会报错：

b.core.windows.net on 127.0.0.11:53: server misbehaving]
[SYS] 2025/03/10 - 00:08:43 | Support for .env file is disabled
[SYS] 2025/03/10 - 00:08:43 | New API v0.4.8.4 started
[SYS] 2025/03/10 - 00:08:43 | using MySQL as database
[SYS] 2025/03/10 - 00:08:43 | database migration started
[SYS] 2025/03/10 - 00:08:43 | database migrated
[SYS] 2025/03/10 - 00:08:43 | SYNC_FREQUENCY not set, use default value 60
[SYS] 2025/03/10 - 00:08:43 | Redis is enabled
[SYS] 2025/03/10 - 00:08:43 | memory cache enabled
[SYS] 2025/03/10 - 00:08:43 | sync frequency: 60 seconds
[SYS] 2025/03/10 - 00:08:43 | channels synced from database
[SYS] 2025/03/10 - 00:08:43 | initializing token encoders
[SYS] 2025/03/10 - 00:08:43 | 正在更新数据看板数据...
[SYS] 2025/03/10 - 00:08:43 | 保存数据看板数据成功，共保存0条数据
[FATAL] 2025/03/10 - 00:08:43 | [failed to get gpt-3.5-turbo token encoder: Get "https://openaipublic.blob.core.windows.net/encodings/cl100k_base.tiktoken": dial tcp: lookup openaipublic.blo

**Comment by Calcium-Ion** [comment]
TIKTOKEN_CACHE_DIR：默认程序启动时会联网下载一些通用的词元的编码，如：gpt-3.5-turbo，在一些网络环境不稳定，或者离线情况，可能会导致启动有问题，可以配置此目录缓存数据，可迁移到离线环境。

https://docs.newapi.pro/installation/environment-variables/?h=tiktoken+dir#_10

**Comment by piwawa** [comment]
> TIKTOKEN_CACHE_DIR：默认程序启动时会联网下载一些通用的词元的编码，如：gpt-3.5-turbo，在一些网络环境不稳定，或者离线情况，可能会导致启动有问题，可以配置此目录缓存数据，可迁移到离线环境。
> 
> https://docs.newapi.pro/installation/environment-variables/?h=tiktoken+dir#_10

为啥设置了 `TIKTOKEN_CACHE_DIR=./tiktoken` 还是在联网下载？

```
version: '3.4'

services:
  new-api:
    image: calciumion/new-api:latest
    container_name: new-api
    restart: always
    command: --log-dir /app/logs
    ports:
      - "34848:3000"
    volumes:
      - ./data:/data
      - ./logs:/app/logs
    environment:
      - SQL_DSN=root:123456@tcp(mysql:3306)/new-api  # Point to the mysql service
      - REDIS_CONN_STRING=redis://redis
      - TZ=Asia/Shanghai
      - RELAY_PROXY=http://127.0.0.1:8889
      - USER_CONTENT_REQUEST_PROXY=http://127.0.0.1:8889
      - TIKTOKEN_CACHE_DIR=./tiktoken

```

```cmd
2025/03/15 20:59:42 /build/model/main.go:177 SLOW SQL >= 200ms
[563.021ms] [rows:0] ALTER TABLE `tokens` MODIFY COLUMN `unlimited_quota` boolean DEFAULT false
[SYS] 2025/03/15 - 20:59:42 | database migrated 
[SYS] 2025/03/15 - 20:59:42 | SYNC_FREQUENCY not set, use default value 60 
[SYS] 2025/03/15 - 20:59:42 | Redis is enabled 
[SYS] 2025/03/15 - 20:59:42 | memory cache enabled 
[SYS] 2025/03/15 - 20:59:42 | sync frequency: 60 seconds 
[SYS] 2025/03/15 - 20:59:42 | channels synced from database 
[SYS] 2025/03/15 - 20:59:42 | initializing token encoders 
[SYS] 2025/03/15 - 20:59:42 | 正在更新数据看板数据... 
[SYS] 2025/03/15 - 20:59:42 | 保存数据看板数据成功，共保存0条数据 
[FATAL] 2025/03/15 - 20:59:52 | [failed to get gpt-3.5-turbo token encoder: Get "https://openaipublic.blob.core.windows.net/encodings/cl100k_base.tiktoken": dial tcp: lookup openaipublic.blob.core.windows.net on 127.0.0.11:53: read udp 127.0.0.1:34409->127.0.0.11:53: i/o timeout] 
 *  终端将被任务重用，按任意键关闭。
```

![Image](https://github.com/user-attachments/assets/817f9f44-6490-40ea-a68a-a4751cc5eeb2)

**Comment by Calcium-Ion** [comment]
你用compose容器启动，又没有自己打包，又不映射路径，容器去哪里找这个文件？

**Comment by piwawa** [comment]
> 你用compose容器启动，又没有自己打包，又不映射路径，容器去哪里找这个文件？

修改后还是不行额

```
version: '3.4'

services:
  new-api:
    image: calciumion/new-api:latest
    container_name: new-api
    restart: always
    command: --log-dir /app/logs
    ports:
      - "34848:3000"
    volumes:
      - ./data:/data
      - ./logs:/app/logs
      - ./tiktoken:/cache/tiktoken
    environment:
      - SQL_DSN=root:123456@tcp(mysql:3306)/new-api  # Point to the mysql service
      - REDIS_CONN_STRING=redis://redis
      - TZ=Asia/Shanghai
      - RELAY_PROXY=http://172.17.0.1:8889
      - USER_CONTENT_REQUEST_PROXY=http://172.17.0.1:8889
      - TIKTOKEN_CACHE_DIR=/cache/tiktoken
```
